disabled_rules: # rule identifiers to exclude from running
  - missing_docs
  - valid_docs
  - function_parameter_count
  - identifier_name
  - trailing_whitespace
  - large_tuple
  - type_body_length
  - empty_enum_arguments
  - shorthand_operator
opt_in_rules: # some rules are only opt-in
  - empty_count
  - todo
  - line_length
  - function_body_length
  - force_unwrapping
  - file_name
  - convenience_type
whitelist_rules:
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
overridden_super_call: error
force_cast: warning # implicitly
file_name: warning
force_unwrapping: error # implicitly
convenience_type: warning
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 120
# they can set both implicitly with an array
function_body_length:
  - 20
  - 50
# or they can set both explicitly
file_length:
  warning: 400
  error: 500
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
variable_name:
  min_length: 3
  max_length: # warning and error
    warning: 40
    error: 50
cyclomatic_complexity:
  warning: 100
  error: 1000
warning_threshold: 100
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
